"""added venue organizer

Revision ID: 4315cb3a0cca
Revises: 69a05374bbc7
Create Date: 2025-09-27 14:04:55.058492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4315cb3a0cca'
down_revision: Union[str, Sequence[str], None] = '69a05374bbc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(), nullable=False))
    op.add_column('events', sa.Column('startDate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('endDate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('venue', sa.String(), nullable=False))
    op.add_column('events', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('events', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('events', sa.Column('long', sa.Float(), nullable=False))
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('events', 'url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('events', 'image',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'title')
    op.drop_column('events', 'latitude')
    op.drop_column('events', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('events', 'image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('events', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('events', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('events', 'long')
    op.drop_column('events', 'lat')
    op.drop_column('events', 'address')
    op.drop_column('events', 'venue')
    op.drop_column('events', 'endDate')
    op.drop_column('events', 'startDate')
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
