"""removed keyword table

Revision ID: 69a05374bbc7
Revises: 6fe54f0d066e
Create Date: 2025-09-23 19:13:05.141111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a05374bbc7'
down_revision: Union[str, Sequence[str], None] = '6fe54f0d066e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keywords')
    op.add_column('events', sa.Column('url', sa.String(), nullable=False))
    op.add_column('events', sa.Column('image', sa.String(), nullable=False))
    op.add_column('events', sa.Column('organizer', sa.String(), nullable=False))
    op.drop_column('events', 'author')
    op.drop_column('events', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('events', 'organizer')
    op.drop_column('events', 'image')
    op.drop_column('events', 'url')
    op.create_table('keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('keywords_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('keywords_pkey'))
    )
    # ### end Alembic commands ###
